version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - pip install mkdocs mkdocs-material

python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: docs/dpulse-docs/mkdocs.yml
